import { S3Client, HeadObjectCommand, PutObjectCommand, GetObjectCommand, DeleteObjectCommand, CopyObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

// The SDK automatically looks up process.env.AWS_ROLE_ARN and logs into AWS securely
const r2Client = new S3Client({ 
    region: "auto", // required value for R2
    endpoint: `https://${process.env.CLOUDFLARE_ID}.r2.cloudflarestorage.com`,
    credentials: {
        accessKeyId: process.env.R2_ACCESS_KEY_ID,
        secretAccessKey: process.env.R2_SECRET_ACCESS_KEY,
    }
});

function isNotFound (error) {
    return error.name === "NotFound"
        || error.name === "NoSuchKey"
        || error.$metadata?.httpStatusCode === 404;
}

function sanitizePath (pathname) {
    return pathname.startsWith("/") ? pathname.slice(1) : pathname;
}

export async function downloadUrl (pathname, ttlseconds = 60) {
    const fileKey = sanitizePath(pathname);
    const command = {
        Bucket: process.env.R2_BUCKET,
        Key: fileKey,
    };
    return await getSignedUrl(r2Client, new GetObjectCommand(command), { expiresIn: ttlseconds });
}

export async function uploadUrl (pathname, ttlseconds = 60) {
    const fileKey = sanitizePath(pathname);
    const command = {
        Bucket: process.env.R2_BUCKET,
        Key: fileKey,
    };
    return await getSignedUrl(r2Client, new PutObjectCommand(command), { expiresIn: ttlseconds });
}

export async function remove (pathname) {
    try {
        const fileKey = sanitizePath(pathname);
        const response = await r2Client.send(new DeleteObjectCommand({
            Bucket: process.env.R2_BUCKET,
            Key: fileKey
        }));
        return response;
    } catch (error) {
        return null;
    }
}

export async function copy (sourcepath, targetpath) {
    try {
        const sourceKey = sanitizePath(sourcepath);
        const targetKey = sanitizePath(targetpath);
        const response = await r2Client.send(new CopyObjectCommand({
            Bucket: process.env.R2_BUCKET,
            CopySource: `${process.env.R2_BUCKET}/${sourceKey}`,
            Key: targetKey
        }));
        return response;
    } catch (error) {
        return isNotFound(error) ? false : null;
    }
}

// returns the an MD5 file hash generated by Cloudflare if exists.
export async function exists (pathname) {
    try {
        const fileKey = sanitizePath(pathname);
        const obj = await r2Client.send(new HeadObjectCommand({
            Bucket: process.env.R2_BUCKET,
            Key: fileKey
        }));
        return obj?.ETag?.replace?.(/"/g, "") || true; // fallback to truthy value if this breaks for some reason. As long as the command didn't fail, the object exists.
    } catch (error) {
        return isNotFound(error) ? false : null;
    }
}
