@bot_token = {{$dotenv bot_token}}
@app_id = {{$dotenv app_id}}
@base = https://discord.com/api/v10/applications

###
POST {{base}}/{{app_id}}/commands
Authorization: Bot {{bot_token}}
Content-Type: application/json

{
    "name": "amiadmin",
    "description": "Checks if you are registered as an admin for this application",
    "type": 1
}