@bot_token = {{$dotenv bot_token}}
@app_id = {{$dotenv app_id}}
@base = https://discord.com/api/v10/applications

@command_id = 1543155275412934728

###
DELETE {{base}}/{{app_id}}/commands/{{command_id}}
Authorization: Bot {{bot_token}}
Content-Type: application/json