name: Automatically Approve Labels

on:
  pull_request_target:
    types: [opened, synchronized, labeled]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - name: Check file paths
        uses: dorny/paths-filter@v3
        id: changes
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          filters: |
            doc_dir:
              - "docs/**/*.md"
              - "*.md"

      - name: Native Auto Approve
        if: |
          contains(github.event.pull_request.labels.*.name, 'force') ||
          (contains(github.event.pull_request.labels.*.name, 'documentation') && steps.changes.outputs.doc_dir == 'true')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve --body "Auto-approved by GitHub Actions workflow condition." --repo ${{ github.repository }}
